---
- name: Create MariaDB data directory
  ansible.builtin.file:
    path: "{{ mariadb_docker_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Run MariaDB container
  community.docker.docker_container:
    name: "{{ mariadb_docker_container_name }}"
    image: "{{ mariadb_docker_image }}"
    restart_policy: always
    env:
      MARIADB_ROOT_PASSWORD: "{{ mariadb_docker_root_password }}"
    volumes:
      - "{{ mariadb_data_dir }}:/var/lib/mysql"
    ports:
      - "{{ mariadb_docker_port }}:3306"
    state: started
